url: https://thoughtproduction.se
baseurl:

# Site settings
title: Thought
email: hello@thoughtproduction.se
description: "Thought is a digital production studio focused on building data-driven apps and experiences."


# Team names, titles and social links
people:
- name: Tyler Wolf
  pic: 1
  position: Founder, Experience Design
  social:
    - title: twitter
      url: https://twitter.com/tylernwolf
    - title: linkedin
      url: https://linkedin.com/in/tylernwolf

- name: Adam Ekberg
  pic: 2
  position: Developer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/adam-ekberg-26a376a0

- name: Stefan Le Noach
  pic: 3
  position: Developer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/stefanlenoach

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social: #
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Fabrikörvägen 4B
  - line: 131 52 Nacka Strand

# Build settings
markdown: kramdown
permalink: pretty